spring.application.name=spring-boot-configprops-diff-notations

my.props.underscores.prop-with-underscores-1=prop-with-underscores-1 hyphen value
my.props.underscores.prop-with-underscores-two=prop-with-underscores-two hyphen value
my.props.underscores.listPropWithUnderscoresThree[0]=prop-with-underscores-three camelCase value
my.props.underscores.list_prop_with_underscores_three[1]=prop-with-underscores-three underscores value
my.props.underscores.inner-pojo.pojo-prop= inner-pojo.pojo-prop hyphen
my.props.underscores.map_prop_with_underscores_four.key1 = map.key1
## these properties are actually duplicates:
my.props.underscores.map-prop-with-underscores-four.some-key= map some-key value
my.props.underscores.map_prop_with_underscores_four.some_key= map some_key value
my.props.underscores.mapPropWithUnderscoresFour.someKey= map someKey value

my.props.ctor.underscores.propWithUnderscores1= ctor prop-with-underscores-1 camelCase value
my.props.ctor.underscores.prop_with_underscores_two= ctor prop-with-underscores-two underscore value
my.props.ctor.underscores.list-prop-with-underscores-three[0]=ctor prop-with-underscores-two hyphen list
my.props.ctor.underscores.map-prop-with-underscores-four.some-key1= map some-key1 hyphen value
my.props.ctor.underscores.map_prop_with_underscores_four.some_key2= map some_key2 underscore value
my.props.ctor.underscores.mapPropWithUnderscoresFour.someKey3= map someKey3 camelCase value

custom.config.myPropOne= camelCase prop1
custom.config.myPropTwo= camelCase prop2
custom.config.my_prop_three= underscore prop3
